# Generated by Django 4.0.6 on 2022-08-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('user_email', models.EmailField(max_length=50, verbose_name='Электронная почта')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('sending_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время отправки')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
